config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[show index edit update] do
    resources :matches, only: %i[new create destroy] do
      resources :messages, only: %i[create]
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_buddies_card.html.erb
<div class="container p-0">
  <div class="b-cards ml-0 mt-2 mb-4 mr-4">
    <div class="b-card">
        <% if user.photo.attached? %>
          <%= image_tag user.photo, class: "avatar avatar-medium-profile", alt: "avatar", style: 'object-fit: cover;' %>
        <% else %>
          <%= image_tag('https://source.unsplash.com/random/120x120')%>
        <% end %>
        <div class="b-card-content">
          <%= link_to(user) do %>
            <h2 class="d-flex justify-content-between"><%= user.name %>,&nbsp;&nbsp; <%= render "shared/flag", language: "#{user.native_language.name}", flag_class: "flag-big"%>
            <span class=""><i><%= link_to '', user_match_path(user), class: "far fa-times-circle b-card-action-3", style: "font-size: 30px", method: :delete, data: { confirm: "Are you sure you want to remove this buddy?"}%></i></span></h2>
          <% end %>
          <p class="pb-0 mb-0"><%= user.address %></p>
            <div class="d-flex ml-1" style="width: 430px">
             <div class="b-circle"></div>
            <%# pluck the buddy's id with reflex from here %>
              <p class="b-card-action-1 mb-0" style="cursor: pointer" data-reflex-permanent data-reflex="click->ChatReflex#update" data-match="<%= user.id %>" data-chatroomId="<%= match[0].id %>"><i class="fas fa-comment" style="font-size: 30px;"></i></p>
              <p class="video-call-button b-card-action-2 video-button mb-0" data-user-id="<%= user.id %>"><i class="fas fa-video" style="font-size: 30px;"></i></p>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_buddy_added_flash.html.erb
  Added <%= user.name %> as a buddy. 
  Head to your <%= link_to "profile page", user_path(current_user) %> and start chatting!

app/views/shared/_flag.html.erb
<%= image_tag "flags/#{language}.svg", alt: "#{language} flag", class: flag_class %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 mb-5" role="alert">
    <%= sanitize notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 mb-5" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <%# the icons on the left %>
    <%=link_to "", root_path, class: "fab fa-twitter" %>
    <%=link_to "", root_path, class: "fab fa-linkedin" %>
    <%=link_to "", root_path, class: "fab fa-facebook" %>
    <%=link_to "", root_path, class: "fab fa-youtube" %>
    <%=link_to "", root_path, class: "fab fa-instagram" %>
    <%# the text on the right %>
  </div>
  <div class=" footer footer-text">
    <%= link_to  "Privacy policy", root_path, class: "mr-5" %> 
    <%= link_to  "Jobs", root_path, class: "mr-5"%>
    <%= link_to  "Terms of Service", root_path, class: "mr-0" %>
  </div>
</div>

app/views/shared/_footer_html.erb
<div class="footer">
  <p>some text inside here</p>
</div>

app/views/shared/_footer_not_fixed.html.erb
<div class="footer style="right: 0; bottom: 0; left: 0; z-index: 1030;">
  <div class="footer-links">
    <%# the icons on the left %>
    <%=link_to "", root_path, class: "fab fa-twitter" %>
    <%=link_to "", root_path, class: "fab fa-linkedin" %>
    <%=link_to "", root_path, class: "fab fa-facebook" %>
    <%=link_to "", root_path, class: "fab fa-youtube" %>
    <%=link_to "", root_path, class: "fab fa-instagram" %>
    <%# the text on the right %>
  </div>
  <div class=" footer footer-text">
    <%= link_to  "Privacy policy", root_path, class: "mr-5" %> 
    <%= link_to  "Jobs", root_path, class: "mr-5"%>
    <%= link_to  "Terms of Service", root_path, class: "mr-0" %>
  </div>
</div>

app/views/shared/_gbordercard.html.erb
<% if user_signed_in? %>
  <%= link_to(user) do %>
  <div class="c-container" style="text-decoration: none;">
    <div class="c-box">
      <% if user.photo.attached? %>
        <%= image_tag user.photo, class: "avatar avatar-large-profile", alt: "avatar", style: 'object-fit: cover;' %>
      <% else %>
      <%= image_tag('https://source.unsplash.com/random/150x150')%>
      <% end %>
      <div class="c-content">
        <div class="c-details">
          <h2><%= user.name %>, <%= user.age %> <span style="color: #7F7F7F; font-weight: 200;">&nbsp;|&nbsp;</span> <strong class="pl-8"> <%= current_user.match_percentage(user) %> % </strong>  </h2>
          <h3><%= user.address %></h3>
          <p><strong><%= user.native_language.name.capitalize %></strong> looking to learn <strong><%= user.target_language.name.capitalize %></strong></p>
          <br>
          <br>
          <p>[ level in <strong> <%= user.target_language.name %> </strong>: <%= user.target_language_level %> ]</p>
        </div>
        <%= link_to 'Add', user_matches_path(user, @match), class: "add-button", method: :post %>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/shared/_interests_grey_boxes.html.erb
<ul class="grey-box">
   <% interests.each do |interest|%>
      <li class="grey-box-list mb-5" style="line-height:75px;">
         <%= interest %>
      </li>                
   <% end %>                 
</ul>

app/views/shared/_interests_purple_boxes.html.erb
<ul class="purple-box">
   <% interests.each do |interest|%>
      <li class="purple-box-list mb-5" style="line-height:60px;">
         <%= interest %>
      </li>                
   <% end %>                 
</ul>

app/views/shared/_mapcard.html.erb
   <div class="c-container" style="text-decoration: none;">
    <div class="c-box" style="height: 400px;"> 
      <div class="c-content">
        <div class="rounded" id="map"
          style="width: 100%; height: 350px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
  

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-dark navbar-expand-sm navbar-light navbar-lewagon sticky-top">
    <%= link_to root_path, class: "navbar-brand" do %>
    <div class="logo-navbar"></div>
    <div class="logo-text"></div>
      <% end %>

    <div class="d-flex">
      <div class="grey-box-list mb-5">
        <p style="cursor: pointer; position: relative"><i> <%= link_to '', user_path(current_user, focus: "buddies"), id: "notifs", class: "fas fa-envelope b-card-action-default", data: { target: "notification.mail" } %></i></p>
      </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-dark navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user) do %>
            <% if current_user.photo.attached? %>
              <%= image_tag current_user.photo, class: "avatar-navbar border border-white mr-2", alt: "avatar", style: 'object-fit: cover;' %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar-navbar border border-white mr-2" %>
            <% end %>
          <% end %>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
            <div class="dropdown-menu dropdown-menu-right animate slideIn" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", user_path(current_user), class: "dropdown-item " %>
              <%= link_to "Edit my profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Find a buddy", users_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_tab_items.html.erb
<div class="mt-3 ml-5 mb-3">

  <% if @user.buddies.count == 0 %>
  <p class="mt-3">You don't have any buddies yet!</p>
  <p class="mb-5">Let's fix that!</p>
  <%= link_to "Find a buddy", users_path, class: "button-purple"%>
  <% else %>
  <div data-controller="chat">
    <div class="container pl-0" style="position: relative;" >
      <%# <h6 class="m-0" style="color: #7E27C4; font-size: 20px">YOUR BUDDIES&nbsp; &nbsp;<i class="far fa-hand-point-left" style="color: #7E27C4; font-size: 20px;"></i></h6><br> %>
      <% @user.buddies.each do |user| %>
      <%= render 'shared/buddies_card', user: user, match: user.find_match(@user) %>
      <%# BELOW HERE IS CODE FOR CHAT  %>
      <% end %>
    </div>

    <div class="container-chat" style="margin-left: 95px; margin-top: 30px;"> 
      <% match = @user.find_match(@buddy) %>
    <div class= "container-chat-top">
      <div class="chat-top-content  d-flex justifty-space-between">
      <% if @buddy.photo.attached? %>
      <%= image_tag @buddy.photo, class: "avatar avatar-large-profile", alt: "avatar", style: 'object-fit: cover;' %>
      <% else %>
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar avatar-large", alt: "avatar" %>
      <% end %>
      <p style="font-size: 20px";> <%= @buddy.name %> </p>
      </div>
    </div>
    <br>
    <br>
    <div class="messages">
      <div id="messages" data-currentuser-id= "<%= current_user.id %>" data-chatroom-id="<%= match[0].id %>">
        <% match[0].messages.each do |message| %>
        <%# Current messages %>
        <%= render 'messages/message', message: message %>
        <% end %>
        <%# Chat entry field %>
        </div>
        <div class="entry-field">
          <%= simple_form_for [ @user, match[0], @message ], remote: false, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>
          <%= f.input :content, as: :string, label: false, placeholder: "Type a message..", class: "form-inline" %>
          <%= f.submit 'Send', id: "send-msg", class: "ml-2 button-chat", style: "margin-bottom: 2px", data: { disable_with: false } %>
          <% end %>
        </div>
        <%# ABOVE HERE IS CODE FOR CHAT %>
    <% end %>
    </div>
    </div>
  </div>
</div>